# Generated by Django 5.1.6 on 2025-03-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_hospital_doctor_contact_doctor_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(default='unkown doc', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(),
        ),
    ]
